### ISSUE TITLE
api.speedtest.io availability

### ISSUE THREAD

**Issue by shaftoe** [alexzaworski/PageSpeed-Badges#4]
Thanks for the cool idea. I see it doesn't work at the moment, I suppose it's not maintained anymore. Any plans to bring it back online?

**Comment by alexzaworski** [comment]
Hi,

The old badges should still be available but often fail to load the first time due to a timeout.

This is because the backend is powered by AWS lambda and there are timing restrictions I cannot get around without some sort of caching on my end.

This project is in fact unmaintained but I do have longterm plans to bring it back powered by the lighthouse API (which would mean you could do accessibility badges too!), but there's a bunch of work to do and it's not a priority for me at the moment.

**Comment by shaftoe** [comment]
Understood, thanks for the quick reply
